# Default profile
spring:
  application:
    name:be-auth
  datasource:
#    url: jdbc:mysql://localhost:3306/be_auth?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/be_auth?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: localhost
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use-new-id-generator-mappings: true
    open-in-view: false
server:
  port: 8777
app:
  jwt:
     secret: YWx3YXlzLXNldC1hLXNlY3JldC13aXRoLWVub3VnaC1sZW5ndGg=
  jwtExpirationMs: 86400000
  jwtRefreshExpirationMs: 120000